### ISSUE TITLE
Visual Bug during a craft of multiple items...

### ISSUE THREAD

**Issue by Fireztonez** [drcrazy/sct#1]
Hello,
I have Smart Crafting Table installed in my modpack and, I just craft 8 crate from BDS&M and a strange visual bug appeared, each time I take 1 item in the output, the items in the input slot shows like Duped, at the end, I saw 6 stack of 130 Living Wood Planks (This is a recipe add by Crafttweaker...).
Here I have a clip of what happened:
https://clips.twitch.tv/AgreeableRelentlessPterodactylKAPOW

So, like you can see, this is just a visual bug, but this is still a little bit scary... You might want to check this glitch out.

Version:
Smart Crafting Table: 1.1.0
Minecraft Forge: 14.23.5.2838
Crafttweaker: 4.1.18
Fastworkbench: 1.7.2

If you need any other information, let me know.

Thanks for your great mod,
Fireztonez

**Comment by drcrazy** [comment]
Thank you for video. It is quite explanatory. I'll look into this.

**Comment by Fireztonez** [comment]
Thank's for that update, I will try that!!
